#	Requête faite par Ahmat IZZEDINE ISSA

PREFIX time: <http://www.w3.org/2006/time#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX time: <http://www.w3.org/2006/time#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ex: <http://example.org/>
PREFIX tio: <http://purl.org/tio/ns#>

SELECT   ?depart ?arrive ?nbVols
WHERE {
  ?x tio:from ?depart;	#	Pays de déaprt 
     ex:unit "FLIGHT";	#	Unité en nombre de vols
     ex:measuredMetric "CAF_PAS_ARR";	#	Vols commerciaux de passagers arrivés
     tio:to ?arrive;	#	Pays de destination 
     rdf:value ?nbVols;	# Le nombre de vols
     time:year ?year.
  
  #	Filtrage est base sur l'année 2016 et le pays de destination
  # doit avoir accueir au moins cinq vols
  FILTER(?year = 2016 && ?nbVols >= 5 )	 
}
ORDER BY ASC(?nbVols)	#	Tri par ordre croissant de nombre de vols
LIMIT 30	#	Limitation à 30 résultats
