#	Requête faite par Alan PROVOST

PREFIX time: <http://www.w3.org/2006/time#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ex: <http://example.org/>
PREFIX tio: <http://purl.org/tio/ns#>

SELECT ?to ?nbFlight
WHERE {
  ?x tio:from "FR";		#Vols partant de France
     ex:unit "FLIGHT";	#Unité en nombre de vols
     ex:measuredMetric "CAF_PAS";	#Vols commerciaux de passagers
     tio:to ?to; 				#Récupération de la destination
     rdf:value ?nbFlight; 		#Récupération du nombre de vols
     time:year ?year.
  
  FILTER(?year = 2021) #Filtrage des années pour que l'année corresponde à 2021
}

ORDER BY DESC(?nbFlight) #Tri par ordre decroissant de nombre de vols
LIMIT 20 #Limitation à 20 résultats
