#	Requête faite par Ahmat IZZEDINE ISSA

PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX ex: <http://example.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

#	Affichage de nombre des sièges passagers offerts qui est superieur à 100 000
#	par ordre croissant en 2020 et l'affichage est limité à 40 entitées

SELECT ?countryName ?icao ?nbOfSeat
WHERE {
	#	Récuperation de nombre de siégés passagers offerts.
	?x	dbo:year    2020;
      	ex:declarativeAirport ?airport;
		ex:measuredMetric "ST_PAS";
  		ex:coverageTransport "TOTAL";
		ex:airline "TOTAL";
		rdf:value    ?nbOfSeat.
	#	Récuperation de code de pays et de l'dentifant des aéroports
  	?airport	dbo:country ?countryName;
				dbo:icaoLocationIdentifier ?icao.
	FILTER(?nbOfSeat>=100000)
}

ORDER BY ASC (?nbOfSeat)
LIMIT 40